In [1]:
#1. Import the NUMPY package under the name np.
import numpy as np

In [2]:
#2. Print the NUMPY version and the configuration.
np.version.version

'1.18.2'

In [3]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

a=np.random.random((2, 3, 5))


In [4]:
#4. Print a.
print(a)

[[[0.37279776 0.51735336 0.89009432 0.29282234 0.18421351]
  [0.42973634 0.5071805  0.23112441 0.31888431 0.66750821]
  [0.05655978 0.17796014 0.06902756 0.31598348 0.82981526]]

 [[0.42594511 0.87203256 0.79764927 0.35917516 0.7338163 ]
  [0.20747955 0.28130479 0.39750444 0.85556281 0.51935297]
  [0.84189688 0.94797885 0.53060296 0.30711641 0.50411619]]]


In [5]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

b=np.full((5,2,3),1)


In [6]:
#6. Print b.
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


In [7]:
#7. Do a and b have the same size? How do you prove that in Python code?
print(a.size)
print(b.size)

if a.size == b.size:
    print("a and b have the same size of: {} values each".format(a.size))
else:
    print("a and b do not have the same size")

30
30
a and b have the same size of: 30 values each


In [9]:
#8. Are you able to add a and b? Why or why not?
sumaab = np.add(a,b)
print (sumaab)

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

you can not add a and b because they do not have the same shame

In [10]:
#9. Transpose b so that it has 
#the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c"."""

b.T.shape

(3, 2, 5)

In [11]:
c=b.reshape((2, 3, 5))
c

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [12]:
c.shape

(2, 3, 5)

In [13]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?
d = np.add(a,c)
print (d)

[[[1.37279776 1.51735336 1.89009432 1.29282234 1.18421351]
  [1.42973634 1.5071805  1.23112441 1.31888431 1.66750821]
  [1.05655978 1.17796014 1.06902756 1.31598348 1.82981526]]

 [[1.42594511 1.87203256 1.79764927 1.35917516 1.7338163 ]
  [1.20747955 1.28130479 1.39750444 1.85556281 1.51935297]
  [1.84189688 1.94797885 1.53060296 1.30711641 1.50411619]]]


it works now because a and d have the same shape

In [14]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

print(a)
print("\n\n")
print(d)


[[[0.37279776 0.51735336 0.89009432 0.29282234 0.18421351]
  [0.42973634 0.5071805  0.23112441 0.31888431 0.66750821]
  [0.05655978 0.17796014 0.06902756 0.31598348 0.82981526]]

 [[0.42594511 0.87203256 0.79764927 0.35917516 0.7338163 ]
  [0.20747955 0.28130479 0.39750444 0.85556281 0.51935297]
  [0.84189688 0.94797885 0.53060296 0.30711641 0.50411619]]]



[[[1.37279776 1.51735336 1.89009432 1.29282234 1.18421351]
  [1.42973634 1.5071805  1.23112441 1.31888431 1.66750821]
  [1.05655978 1.17796014 1.06902756 1.31598348 1.82981526]]

 [[1.42594511 1.87203256 1.79764927 1.35917516 1.7338163 ]
  [1.20747955 1.28130479 1.39750444 1.85556281 1.51935297]
  [1.84189688 1.94797885 1.53060296 1.30711641 1.50411619]]]


d values are the result of a values added by 1

In [15]:
#12. Multiply a and c. Assign the result to e.
e=np.matmul(a.T,c)
e

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

In [16]:

print(a.T.shape)
print(c.shape)


(5, 3, 2)
(2, 3, 5)


In [17]:
#13. Does e equal to a? Why or why not?

In [18]:
#14. Identify the max, min, and mean values in d. Assign those values to variables 
d_max= np.max(d)
d_min= np.min(d)
d_mean= np.mean(d)

print(d,"\n")

print(d_max, d_min, d_mean)

[[[1.37279776 1.51735336 1.89009432 1.29282234 1.18421351]
  [1.42973634 1.5071805  1.23112441 1.31888431 1.66750821]
  [1.05655978 1.17796014 1.06902756 1.31598348 1.82981526]]

 [[1.42594511 1.87203256 1.79764927 1.35917516 1.7338163 ]
  [1.20747955 1.28130479 1.39750444 1.85556281 1.51935297]
  [1.84189688 1.94797885 1.53060296 1.30711641 1.50411619]]] 

1.9479788471011705 1.056559780302435 1.4814198516145918


In [19]:
#15. Now we want to label the values in d. 
#First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

f=np.empty((2,3,5))

f

array([[[1.37279776, 1.51735336, 1.89009432, 1.29282234, 1.18421351],
        [1.42973634, 1.5071805 , 1.23112441, 1.31888431, 1.66750821],
        [1.05655978, 1.17796014, 1.06902756, 1.31598348, 1.82981526]],

       [[1.42594511, 1.87203256, 1.79764927, 1.35917516, 1.7338163 ],
        [1.20747955, 1.28130479, 1.39750444, 1.85556281, 1.51935297],
        [1.84189688, 1.94797885, 1.53060296, 1.30711641, 1.50411619]]])

In [20]:
"""
#16. Populate the values in f. For each value in d, 

if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.

If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.

If a value equals to d_mean, assign 50 to the corresponding value in f.

Assign 0 to the corresponding value(s) in f for d_min in d.

Assign 100 to the corresponding value(s) in f for d_max in d.

In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.
"""
dflat = d.flatten()
fflat = f.flatten()


for i in range(len(dflat)):
    if dflat[i] > d_min and dflat[i] < d_mean:
        fflat[i] = 25
    elif dflat[i] > d_mean and dflat[i] < d_max:
        fflat[i] = 75
    elif dflat[i] == d_mean:
        fflat[i] = 50
    elif dflat[i] == d_max:
        fflat[i] = 100
    elif dflat[i] == d_min:
        fflat[i] = 0


f=np.array(fflat)

f = f.reshape(2,3,5)


In [21]:
"""
#17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])
"""

print(d_max, d_min, d_mean)
print("\n")
print(d)
print("\n")
print(f)


1.9479788471011705 1.056559780302435 1.4814198516145918


[[[1.37279776 1.51735336 1.89009432 1.29282234 1.18421351]
  [1.42973634 1.5071805  1.23112441 1.31888431 1.66750821]
  [1.05655978 1.17796014 1.06902756 1.31598348 1.82981526]]

 [[1.42594511 1.87203256 1.79764927 1.35917516 1.7338163 ]
  [1.20747955 1.28130479 1.39750444 1.85556281 1.51935297]
  [1.84189688 1.94797885 1.53060296 1.30711641 1.50411619]]]


[[[ 25.  75.  75.  25.  25.]
  [ 25.  75.  25.  25.  75.]
  [  0.  25.  25.  25.  75.]]

 [[ 25.  75.  75.  25.  75.]
  [ 25.  25.  25.  75.  75.]
  [ 75. 100.  75.  25.  75.]]]


In [22]:
"""#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.
"""

dflat = d.flatten()
fflat = f.flatten()
fextra =[]


for i in range(len(dflat)):
    if dflat[i] > d_min and dflat[i] < d_mean:
        fextra.append("B")
    elif dflat[i] > d_mean and dflat[i] < d_max:
        fextra.append("D")
    elif dflat[i] == d_mean:
        fextra.append("C")
    elif dflat[i] == d_max:
        fextra.append("E")
    elif dflat[i] == d_min:
        fextra.append("A")

ffinal = np.array(fextra)

ffinal = ffinal.reshape(2,3,5)

print(ffinal)

[[['B' 'D' 'D' 'B' 'B']
  ['B' 'D' 'B' 'B' 'D']
  ['A' 'B' 'B' 'B' 'D']]

 [['B' 'D' 'D' 'B' 'D']
  ['B' 'B' 'B' 'D' 'D']
  ['D' 'E' 'D' 'B' 'D']]]
