In [0]:
#1. Import the NUMPY package under the name np.
import numpy as np

In [18]:
#2. Print the NUMPY version and the configuration.
print(np.version.version)
print(np.show_config())

1.18.2
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
None


In [0]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?
a=np.random.random((2,3,5))


In [20]:
#4. Print a.
print(a)

[[[0.37735949 0.44642841 0.93645346 0.43144129 0.07159207]
  [0.50553233 0.55539506 0.33926252 0.71097167 0.94654418]
  [0.59453128 0.79222924 0.55001705 0.50612262 0.86081971]]

 [[0.82645345 0.2917011  0.48278816 0.1645855  0.05495623]
  [0.5004374  0.61629417 0.04170947 0.34778184 0.52664053]
  [0.86920109 0.97206664 0.63891696 0.32880747 0.99946494]]]


In [0]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"
b=np.full((5,3,2), 1)

In [22]:
#6. Print b.
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


In [24]:
#7. Do a and b have the same size? How do you prove that in Python code?
a.size==b.size

True

In [25]:
#8. Are you able to add a and b? Why or why not?
#No, porque sus dimensiones no lo permiten. uno es de (2,3,5) y el otro es (5,3,2)
a+b

ValueError: ignored

In [29]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".
c=b.transpose()
print(c)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


In [30]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?
#Because now their dimensions match
d=a+c
print(d)

[[[1.37735949 1.44642841 1.93645346 1.43144129 1.07159207]
  [1.50553233 1.55539506 1.33926252 1.71097167 1.94654418]
  [1.59453128 1.79222924 1.55001705 1.50612262 1.86081971]]

 [[1.82645345 1.2917011  1.48278816 1.1645855  1.05495623]
  [1.5004374  1.61629417 1.04170947 1.34778184 1.52664053]
  [1.86920109 1.97206664 1.63891696 1.32880747 1.99946494]]]


In [31]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.
#Cada elemento de a se sumó a un elemento de c(que en su origen fue b) por lo que el resultado es igual 
#a todos los valores de a+1
print(a)
print(d)

[[[0.37735949 0.44642841 0.93645346 0.43144129 0.07159207]
  [0.50553233 0.55539506 0.33926252 0.71097167 0.94654418]
  [0.59453128 0.79222924 0.55001705 0.50612262 0.86081971]]

 [[0.82645345 0.2917011  0.48278816 0.1645855  0.05495623]
  [0.5004374  0.61629417 0.04170947 0.34778184 0.52664053]
  [0.86920109 0.97206664 0.63891696 0.32880747 0.99946494]]]
[[[1.37735949 1.44642841 1.93645346 1.43144129 1.07159207]
  [1.50553233 1.55539506 1.33926252 1.71097167 1.94654418]
  [1.59453128 1.79222924 1.55001705 1.50612262 1.86081971]]

 [[1.82645345 1.2917011  1.48278816 1.1645855  1.05495623]
  [1.5004374  1.61629417 1.04170947 1.34778184 1.52664053]
  [1.86920109 1.97206664 1.63891696 1.32880747 1.99946494]]]


In [33]:
#12. Multiply a and c. Assign the result to e.
e=np.multiply(a,c)
print(e)

[[[0.37735949 0.44642841 0.93645346 0.43144129 0.07159207]
  [0.50553233 0.55539506 0.33926252 0.71097167 0.94654418]
  [0.59453128 0.79222924 0.55001705 0.50612262 0.86081971]]

 [[0.82645345 0.2917011  0.48278816 0.1645855  0.05495623]
  [0.5004374  0.61629417 0.04170947 0.34778184 0.52664053]
  [0.86920109 0.97206664 0.63891696 0.32880747 0.99946494]]]


In [34]:
#13. Does e equal to a? Why or why not?
#Sì es igual, porque c contiene únicamente 1 y se está multiplicando por a
print(e==a)

[[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]


In [35]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"
d_max=d.max()
d_min=d.min()
d_mean=np.mean(d)
print(d_max)
print(d_min)
print(d_mean)

1.999464942462808
1.0417094749399518
1.5428835115355048


In [39]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.
f=np.empty([2,3,5])
print(f)

[[[0.37735949 0.44642841 0.93645346 0.43144129 0.07159207]
  [0.50553233 0.55539506 0.33926252 0.71097167 0.94654418]
  [0.59453128 0.79222924 0.55001705 0.50612262 0.86081971]]

 [[0.82645345 0.2917011  0.48278816 0.1645855  0.05495623]
  [0.5004374  0.61629417 0.04170947 0.34778184 0.52664053]
  [0.86920109 0.97206664 0.63891696 0.32880747 0.99946494]]]


In [62]:
for i in range(2):
  for j in range(3):
    for k in range(5):
      #print(d[i,j,k])
      if d[i,j,k] > d_min and d[i,j,k] < d_mean:
        f[i,j,k]=25
      elif d[i,j,k] > d_mean and d[i,j,k] < d_max:
        f[i,j,k]=75
      elif d[i,j,k]==d_min:
        f[i,j,k]=0
      elif d[i,j,k]==d_max:
        f[i,j,k]=100
      elif d[i,j,k]==d_mean:
        f[i,j,k]=50

print(d)
print(f.astype(int))

[[[1.37735949 1.44642841 1.93645346 1.43144129 1.07159207]
  [1.50553233 1.55539506 1.33926252 1.71097167 1.94654418]
  [1.59453128 1.79222924 1.55001705 1.50612262 1.86081971]]

 [[1.82645345 1.2917011  1.48278816 1.1645855  1.05495623]
  [1.5004374  1.61629417 1.04170947 1.34778184 1.52664053]
  [1.86920109 1.97206664 1.63891696 1.32880747 1.99946494]]]
[[[ 25  25  75  25  25]
  [ 25  75  25  75  75]
  [ 75  75  75  25  75]]

 [[ 75  25  25  25  25]
  [ 25  75   0  25  25]
  [ 75  75  75  25 100]]]


In [63]:
faux=f.tolist()

for i in range(2):
  for j in range(3):
    for k in range(5):
      #print(d[i,j,k])
      if d[i,j,k] > d_min and d[i,j,k] < d_mean:
        faux[i][j][k]='B'
      elif d[i,j,k] > d_mean and d[i,j,k] < d_max:
        faux[i][j][k]='D'
      elif d[i,j,k]==d_min:
        faux[i][j][k]='A'
      elif d[i,j,k]==d_max:
        faux[i][j][k]='E'
      elif d[i,j,k]==d_mean:
        faux[i][j][k]='C'

res=np.array(faux)
print(res)


[[['B' 'B' 'D' 'B' 'B']
  ['B' 'D' 'B' 'D' 'D']
  ['D' 'D' 'D' 'B' 'D']]

 [['D' 'B' 'B' 'B' 'B']
  ['B' 'D' 'A' 'B' 'B']
  ['D' 'D' 'D' 'B' 'E']]]
