In [2]:
import numpy as np


In [3]:
a=np.random.random((2,3,5))
print(a)
b= np.ones((5, 3, 2))
print(b)


[[[0.13716489 0.58425735 0.20874817 0.1967259  0.1084873 ]
  [0.72554532 0.38772315 0.74943138 0.51121028 0.25422456]
  [0.33844387 0.1535054  0.28969763 0.81380849 0.26497951]]

 [[0.09853393 0.83266753 0.52294198 0.62799798 0.42876458]
  [0.56843509 0.48712624 0.95709679 0.71818195 0.97004326]
  [0.67600088 0.60471127 0.04394069 0.74673705 0.66346359]]]
[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [4]:
c=b.T
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [8]:

d= np.add(a,c)
print(d)

[[[1.13716489 1.58425735 1.20874817 1.1967259  1.1084873 ]
  [1.72554532 1.38772315 1.74943138 1.51121028 1.25422456]
  [1.33844387 1.1535054  1.28969763 1.81380849 1.26497951]]

 [[1.09853393 1.83266753 1.52294198 1.62799798 1.42876458]
  [1.56843509 1.48712624 1.95709679 1.71818195 1.97004326]
  [1.67600088 1.60471127 1.04394069 1.74673705 1.66346359]]]


In [6]:
#a==b o bien np.array_equal(a, b)

/Users/enrique/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  """Entry point for launching an IPython kernel.


False

In [9]:
print(a)
print(d)

[[[0.13716489 0.58425735 0.20874817 0.1967259  0.1084873 ]
  [0.72554532 0.38772315 0.74943138 0.51121028 0.25422456]
  [0.33844387 0.1535054  0.28969763 0.81380849 0.26497951]]

 [[0.09853393 0.83266753 0.52294198 0.62799798 0.42876458]
  [0.56843509 0.48712624 0.95709679 0.71818195 0.97004326]
  [0.67600088 0.60471127 0.04394069 0.74673705 0.66346359]]]
[[[1.13716489 1.58425735 1.20874817 1.1967259  1.1084873 ]
  [1.72554532 1.38772315 1.74943138 1.51121028 1.25422456]
  [1.33844387 1.1535054  1.28969763 1.81380849 1.26497951]]

 [[1.09853393 1.83266753 1.52294198 1.62799798 1.42876458]
  [1.56843509 1.48712624 1.95709679 1.71818195 1.97004326]
  [1.67600088 1.60471127 1.04394069 1.74673705 1.66346359]]]


In [10]:
e= a*c
print(e)

[[[0.13716489 0.58425735 0.20874817 0.1967259  0.1084873 ]
  [0.72554532 0.38772315 0.74943138 0.51121028 0.25422456]
  [0.33844387 0.1535054  0.28969763 0.81380849 0.26497951]]

 [[0.09853393 0.83266753 0.52294198 0.62799798 0.42876458]
  [0.56843509 0.48712624 0.95709679 0.71818195 0.97004326]
  [0.67600088 0.60471127 0.04394069 0.74673705 0.66346359]]]


In [11]:
d_max= d.max()
d_min= d.min()
d_mean= d.mean()
print(d_max)
print(d_min)
print(d_mean)

1.9700432612719267
1.0439406938476314
1.4890198669007575


In [21]:
d.shape
f= np.empty((2, 3, 5))
print(f)

[[[0.13716489 0.58425735 0.20874817 0.1967259  0.1084873 ]
  [0.72554532 0.38772315 0.74943138 0.51121028 0.25422456]
  [0.33844387 0.1535054  0.28969763 0.81380849 0.26497951]]

 [[0.09853393 0.83266753 0.52294198 0.62799798 0.42876458]
  [0.56843509 0.48712624 0.95709679 0.71818195 0.97004326]
  [0.67600088 0.60471127 0.04394069 0.74673705 0.66346359]]]


 """
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.
"""



In [28]:
#range para moverme en las entradas de dim.
#d[z,y,x] me agarra toda bolsa
#() de d_min(), etc ya no son necesarios una vez declarados, ya los tenía guardados arriba
#antes en d[z,y,x] tenía x y por cada f[z,y,x] tenía f pero eso no era agarrarme a todos los de la bolsa.. era modificar uno contínuamente y no tenía sentido
for z in range(2):
    for y in range(3):
        for x in range(5):
            if d[z,y,x]>d_min and d[z,y,x]<d_mean:
                f[z, y,x]=25
            elif d_mean<d[z,y,x] and d[z,y,x]<d_max:
                f[z,y,x]=75
            elif d[z,y,x]==d_max:
                f[z,y,x]=100
            elif d[z,y,x]==d_min:
                f[z,y,x]=0
            elif d[z,y,x]==d_mean:
                f[z,y,x]=50
            
print(f)
print(d)
            

[[[ 25.  75.  25.  25.  25.]
  [ 75.  25.  75.  75.  25.]
  [ 25.  25.  25.  75.  25.]]

 [[ 25.  75.  75.  75.  25.]
  [ 75.  25.  75.  75. 100.]
  [ 75.  75.   0.  75.  75.]]]
[[[1.13716489 1.58425735 1.20874817 1.1967259  1.1084873 ]
  [1.72554532 1.38772315 1.74943138 1.51121028 1.25422456]
  [1.33844387 1.1535054  1.28969763 1.81380849 1.26497951]]

 [[1.09853393 1.83266753 1.52294198 1.62799798 1.42876458]
  [1.56843509 1.48712624 1.95709679 1.71818195 1.97004326]
  [1.67600088 1.60471127 1.04394069 1.74673705 1.66346359]]]


In [44]:
#ejercicio 18
#no cambiar las letras sino la estructura: cambiar f`s:
#con cambio de f a g list indices must be integers
g= f.tolist()
for z in range(2):
    for y in range(3):
        for x in range(5):
            if d[z,y,x]>d_min and d[z,y,x]<d_mean:
                g[z][y][x]= "B"
            elif d_mean<d[z,y,x] and d[z,y,x]<d_max:
                g[z][y][x]="C"
            elif d[z,y,x]==d_max:
                g[z][y][x]="E"
            elif d[z,y,x]==d_min:
                g[z][y][x]="0"
            elif d[z,y,x]==d_mean:
                g[z][y][x]="C"
print(g)

# con lógica de: var =np.array(lst_lst)
h= np.array(g)
print(h)

[[['B', 'C', 'B', 'B', 'B'], ['C', 'B', 'C', 'C', 'B'], ['B', 'B', 'B', 'C', 'B']], [['B', 'C', 'C', 'C', 'B'], ['C', 'B', 'C', 'C', 'E'], ['C', 'C', '0', 'C', 'C']]]
[[['B' 'C' 'B' 'B' 'B']
  ['C' 'B' 'C' 'C' 'B']
  ['B' 'B' 'B' 'C' 'B']]

 [['B' 'C' 'C' 'C' 'B']
  ['C' 'B' 'C' 'C' 'E']
  ['C' 'C' '0' 'C' 'C']]]
