In [1]:
import numpy as np

In [4]:
print(np.version.version)

1.16.5


In [5]:
a = np.random.random((2,3,5))

In [6]:
print(a)

[[[0.04304314 0.48450602 0.14728973 0.59553443 0.64720027]
  [0.95275509 0.31900123 0.20822716 0.57114019 0.21086558]
  [0.03325049 0.89843796 0.22065892 0.53468347 0.48438536]]

 [[0.87874169 0.06090788 0.959649   0.59415717 0.64868342]
  [0.30450419 0.39118212 0.83841137 0.52614343 0.87593297]
  [0.35134413 0.98521593 0.03152951 0.70856712 0.44650183]]]


In [8]:
b = np.full((5,2,3), 1)

In [9]:
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


In [10]:
if b.shape == a.shape:
        print(True)
else:
        print(False) 

False


In [11]:
print(np.add(a, b))
print('a + b :operands could not be broadcast together with shapes (2,3,5) (5,2,3)')

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [12]:
c = b.reshape(2,3,5)
print(c.shape)

(2, 3, 5)


In [13]:
d = np.add(a,c)
print(d)
print('Yes, arrays with same structures sizes')

[[[1.04304314 1.48450602 1.14728973 1.59553443 1.64720027]
  [1.95275509 1.31900123 1.20822716 1.57114019 1.21086558]
  [1.03325049 1.89843796 1.22065892 1.53468347 1.48438536]]

 [[1.87874169 1.06090788 1.959649   1.59415717 1.64868342]
  [1.30450419 1.39118212 1.83841137 1.52614343 1.87593297]
  [1.35134413 1.98521593 1.03152951 1.70856712 1.44650183]]]
Yes, arrays with same structures sizes


In [14]:
print('\n',a)
print('\n',d)
print('each value in array "a" is + 1, this value comes from array "c".')


 [[[0.04304314 0.48450602 0.14728973 0.59553443 0.64720027]
  [0.95275509 0.31900123 0.20822716 0.57114019 0.21086558]
  [0.03325049 0.89843796 0.22065892 0.53468347 0.48438536]]

 [[0.87874169 0.06090788 0.959649   0.59415717 0.64868342]
  [0.30450419 0.39118212 0.83841137 0.52614343 0.87593297]
  [0.35134413 0.98521593 0.03152951 0.70856712 0.44650183]]]

 [[[1.04304314 1.48450602 1.14728973 1.59553443 1.64720027]
  [1.95275509 1.31900123 1.20822716 1.57114019 1.21086558]
  [1.03325049 1.89843796 1.22065892 1.53468347 1.48438536]]

 [[1.87874169 1.06090788 1.959649   1.59415717 1.64868342]
  [1.30450419 1.39118212 1.83841137 1.52614343 1.87593297]
  [1.35134413 1.98521593 1.03152951 1.70856712 1.44650183]]]
each value in array "a" is + 1, this value comes from array "c".


In [15]:
e = np.multiply(a, c)

In [16]:
print(e)
print(e==a)

[[[0.04304314 0.48450602 0.14728973 0.59553443 0.64720027]
  [0.95275509 0.31900123 0.20822716 0.57114019 0.21086558]
  [0.03325049 0.89843796 0.22065892 0.53468347 0.48438536]]

 [[0.87874169 0.06090788 0.959649   0.59415717 0.64868342]
  [0.30450419 0.39118212 0.83841137 0.52614343 0.87593297]
  [0.35134413 0.98521593 0.03152951 0.70856712 0.44650183]]]
[[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]


In [31]:
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

In [36]:
f = np.empty([2,3,5])
print(f)

[[[0.04304314 0.48450602 0.14728973 0.59553443 0.64720027]
  [0.95275509 0.31900123 0.20822716 0.57114019 0.21086558]
  [0.03325049 0.89843796 0.22065892 0.53468347 0.48438536]]

 [[0.87874169 0.06090788 0.959649   0.59415717 0.64868342]
  [0.30450419 0.39118212 0.83841137 0.52614343 0.87593297]
  [0.35134413 0.98521593 0.03152951 0.70856712 0.44650183]]]


In [40]:
for x in range(2):
        for y in range(3):
                for z in range(5):
                        if d[x,y,z] == d_max:
                                f[x,y,z] = 100
                        elif d[x,y,z] < d_max and d[x,y,z] > d_mean:
                                f[x,y,z] = 75
                        elif  d[x,y,z] == d_mean:
                                f[x,y,z] = 50
                        elif d[x,y,z] > d_min and d[x,y,z] < d_mean:
                                f[x,y,z] = 25
                        elif d[x,y,z] == d_min:
                                f[x,y,z] = 25
print(f.astype(int))

[[[ 25  25  25  75  75]
  [ 75  25  25  75  25]
  [ 25  75  25  75  25]]

 [[ 75  25  75  75  75]
  [ 25  25  75  75  75]
  [ 25 100  25  75  25]]]


In [44]:
f2 = f.tolist()
for x in range(2):
        for y in range(3):
                for z in range(5):
                        if d[x,y,z] == d_max:
                                f2[x][y][z] = 'E'
                        elif d[x,y,z] < d_max and d[x,y,z] > d_mean:
                                f2[x][y][z] = 'D'
                        elif  d[x,y,z] == d_mean:
                                f2[x][y][z] = 'C'
                        elif d[x,y,z] > d_min and d[x,y,z] < d_mean:
                                f2[x][y][z] = 'B'
                        elif d[x,y,z] == d_min:
                                f2[x][y][z] = 'A'
f2 = np.array(f2)
print(f2)

[[['B' 'B' 'B' 'D' 'D']
  ['D' 'B' 'B' 'D' 'B']
  ['B' 'D' 'B' 'D' 'B']]

 [['D' 'B' 'D' 'D' 'D']
  ['B' 'B' 'D' 'D' 'D']
  ['B' 'E' 'A' 'D' 'B']]]
