In [1]:
import numpy as np

In [6]:
import numpy as np
#2. Print the NUMPY version and the configuration.
print(np.version)
print(np.show_config())
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?
a=np.random.random((2,3,5))
#4. Print a.
print(a)
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"
b=np.full((5,3,2),1)
#6. Print b.
print(b)
#7. Do a and b have the same size? How do you prove that in Python code?
x=a.size
z=b.size
print(x==z)
#8. Are you able to add a and b? Why or why not?
#print(a+b)ValueError: operands could not be broadcast together with shapes (2,3,5) (5,3,2) 
#No, porque sus tamaños o dimensiones no lo permiten
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".
c = b.T
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?
d= a+c
#Funciona ahora porque los 2 arrays tienen la misma estructura (2,3,5)
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.
print(a)
print(d)
#El array de "d" en todos sus valores esta +1, ya que el array de "c" eran solo valores de 1 y al sumarse con a se igualo a "d"
#12. Multiply a and c. Assign the result to e.
e = a*c
#e2 = np.matmul(a,c) porque sale este error?
print(e)
#13. Does e equal to a? Why or why not?
print(e)
print(e==a) #si es igual ya que "c" solamente son valores de 1 asi que al multiplicarse por "1" su valor no cambia
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"
d_max= d.max
d_min= d.min
d_mean= np.mean(d)
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.
f= np.empty([2,3,5])
print(f)
"""
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.
"""

for x in range(2):
        for x3 in range(3):
                for x5 in range (5):
                        if d[x,x3,x5] > d_min and d[x,x3,x5] < d_mean:
                                f [x,x3,x5]= 25
                        elif d[x,x3,x5] > d_mean and d[x,x3,x5] < d_max:
                                f[x,x3,x5] =75
                        elif d[x,x3,x5]==d_min:
                                f[x,x3,x5]=0
                        elif d[x,x3,x5]==d_max:
                                f[x,x3,x5]= 100
                        elif d[x,x3,x5]==d_mean:
                                f [x,x3,x5]=50 
print(f.astype(int))           

<module 'numpy.version' from '/home/david/.local/lib/python3.6/site-packages/numpy/version.py'>
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
None
[[[0.0626431  0.00440627 0.19178291 0.45705522 0.98211399]
  [0.59878706 0.84063565 0.86157044 0.50283329 0.64187519]
  [0.83490316 0.86155343 0.49661278 0.20229357 0.12099841]]

 [[0

TypeError: '>' not supported between instances of 'float' and 'builtin_function_or_method'