In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.16.4


In [3]:
a = np.random.random((2,3,5))

CPU times: user 2 µs, sys: 0 ns, total: 2 µs
Wall time: 4.05 µs


In [5]:
print(np.random.random(30).reshape(2,3,5))

[[[0.32685026 0.53262822 0.42248334 0.03304339 0.97311045]
  [0.17301009 0.03127082 0.45150524 0.62626429 0.28087487]
  [0.99134488 0.93174411 0.73164928 0.92392728 0.1665885 ]]

 [[0.59921373 0.79986411 0.21264948 0.33823435 0.22198975]
  [0.69964556 0.80119397 0.01961262 0.17353107 0.3386617 ]
  [0.8054982  0.20027777 0.10574543 0.81133913 0.10984341]]]


In [6]:
print(np.array([np.random.random() for i in range(30)]).reshape(2,3,5))

[[[0.57788088 0.35126112 0.62200176 0.69418693 0.67074352]
  [0.63656787 0.64494993 0.29037414 0.58948316 0.22991092]
  [0.96285694 0.68165831 0.21338268 0.24902571 0.47269984]]

 [[0.44064973 0.77259466 0.51394948 0.33290077 0.96384974]
  [0.44244757 0.01517139 0.1954673  0.1695896  0.24394588]
  [0.34587205 0.97661403 0.42695831 0.83658582 0.13239977]]]


In [4]:
print(a)

[[[0.93795479 0.23885778 0.4424818  0.51877338 0.67441079]
  [0.09748897 0.97912805 0.43950851 0.97616377 0.86749248]
  [0.33577825 0.57418336 0.93434912 0.01553701 0.64491085]]

 [[0.37227036 0.92133283 0.15621512 0.03607632 0.81182083]
  [0.74595088 0.22896696 0.66813502 0.83866415 0.29202848]
  [0.0457432  0.68759947 0.83229374 0.27051726 0.45529266]]]


In [35]:
b = np.ones((5,2,3))

In [36]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [89]:
print(a.shape == b.shape)

False


In [90]:
print(a+b)

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [40]:
c = np.transpose(b,axes=[1,2,0])

In [84]:
d=a+c

In [50]:
print(a, "\n\n\n\n",d)

[[[0.93795479 0.23885778 0.4424818  0.51877338 0.67441079]
  [0.09748897 0.97912805 0.43950851 0.97616377 0.86749248]
  [0.33577825 0.57418336 0.93434912 0.01553701 0.64491085]]

 [[0.37227036 0.92133283 0.15621512 0.03607632 0.81182083]
  [0.74595088 0.22896696 0.66813502 0.83866415 0.29202848]
  [0.0457432  0.68759947 0.83229374 0.27051726 0.45529266]]] 



 [[[1.93795479 1.23885778 1.4424818  1.51877338 1.67441079]
  [1.09748897 1.97912805 1.43950851 1.97616377 1.86749248]
  [1.33577825 1.57418336 1.93434912 1.01553701 1.64491085]]

 [[1.37227036 1.92133283 1.15621512 1.03607632 1.81182083]
  [1.74595088 1.22896696 1.66813502 1.83866415 1.29202848]
  [1.0457432  1.68759947 1.83229374 1.27051726 1.45529266]]]


In [92]:
e = np.multiply(a,c)

In [52]:
print(e)

[[[0.93795479 0.23885778 0.4424818  0.51877338 0.67441079]
  [0.09748897 0.97912805 0.43950851 0.97616377 0.86749248]
  [0.33577825 0.57418336 0.93434912 0.01553701 0.64491085]]

 [[0.37227036 0.92133283 0.15621512 0.03607632 0.81182083]
  [0.74595088 0.22896696 0.66813502 0.83866415 0.29202848]
  [0.0457432  0.68759947 0.83229374 0.27051726 0.45529266]]]


In [93]:
e == a

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

In [56]:
d_max = d.max();
d_min = d.min();
d_mean = d.mean();

In [65]:
f = np.empty((2,3,5))

In [73]:
d[d_mean>d]

array([1.23885778, 1.4424818 , 1.51877338, 1.09748897, 1.43950851,
       1.33577825, 1.01553701, 1.37227036, 1.15621512, 1.03607632,
       1.22896696, 1.29202848, 1.0457432 , 1.27051726, 1.45529266])

In [75]:
d[d>d_min]

array([1.93795479, 1.23885778, 1.4424818 , 1.51877338, 1.67441079,
       1.09748897, 1.97912805, 1.43950851, 1.97616377, 1.86749248,
       1.33577825, 1.57418336, 1.93434912, 1.64491085, 1.37227036,
       1.92133283, 1.15621512, 1.03607632, 1.81182083, 1.74595088,
       1.22896696, 1.66813502, 1.83866415, 1.29202848, 1.0457432 ,
       1.68759947, 1.83229374, 1.27051726, 1.45529266])

In [78]:
[(d > d_min) & (d < d_mean)].

[array([[[False,  True,  True,  True, False],
         [ True, False,  True, False, False],
         [ True, False, False, False, False]],
 
        [[ True, False,  True,  True, False],
         [False,  True, False, False,  True],
         [ True, False, False,  True,  True]]])]

In [86]:
np.place(f, (d > d_min) & (d < d_mean), 25);
np.place(f, (d > d_mean) & (d < d_max), 75);
np.place(f, (d == d_mean), 50);
np.place(f, (d == d_min), 0);
np.place(f, (d == d_max), 100);

In [87]:
f

array([[[ 75.,  25.,  25.,  25.,  75.],
        [ 25., 100.,  25.,  75.,  75.],
        [ 25.,  75.,  75.,   0.,  75.]],

       [[ 25.,  75.,  25.,  25.,  75.],
        [ 75.,  25.,  75.,  75.,  25.],
        [ 25.,  75.,  75.,  25.,  25.]]])

In [125]:
g = d.copy()
g

array([[[1.93795479, 1.23885778, 1.4424818 , 1.51877338, 1.67441079],
        [1.09748897, 1.97912805, 1.43950851, 1.97616377, 1.86749248],
        [1.33577825, 1.57418336, 1.93434912, 1.01553701, 1.64491085]],

       [[1.37227036, 1.92133283, 1.15621512, 1.03607632, 1.81182083],
        [1.74595088, 1.22896696, 1.66813502, 1.83866415, 1.29202848],
        [1.0457432 , 1.68759947, 1.83229374, 1.27051726, 1.45529266]]])

In [126]:
g[(d > d_min) & (d < d_mean)] = 1;
g[(d > d_mean) & (d < d_max)] = 3;
g[(d == d_mean)] = 2;
g[(d == d_min)] = 0;
g[(d == d_max)] = 4;


In [129]:
dictio = {0:"A", 1:"B", 2:"C", 3:"D", 4:"E"}

In [131]:
h = np.vectorize(dictio.get)(g)

In [132]:
h

array([[['D', 'B', 'B', 'B', 'D'],
        ['B', 'E', 'B', 'D', 'D'],
        ['B', 'D', 'D', 'A', 'D']],

       [['B', 'D', 'B', 'B', 'D'],
        ['D', 'B', 'D', 'D', 'B'],
        ['B', 'D', 'D', 'B', 'B']]], dtype='<U1')

In [123]:
g =np.array(map(g,{0:"A", 1:"B", 2:"C", 3:"D", 4:"E"}))

In [124]:
g

array(<map object at 0x7fe28fd21ac8>, dtype=object)

In [ ]:
let g = Dictionary(uniqueKeysWithValues:
    oldDict.map { key, value in (key.uppercased(), value.lowercased()) })